### ISSUE TITLE
AnalogSignalArray Input Handling

### ISSUE THREAD

**Issue by shayokdutta** [nelpy/nelpy#106]
`cow = np.array([[1,3],[1,3],[1,3,2]])`
`cow.shape`

Above case is still not handled for ydata. Also, tdata is assumed to be one dimensional and the same for all signals passed through via ydata. ydata is also expected to be of shape (numSignals, numDataPoints) while tdata is expected to be of shape (numDataPoints,)

**Comment by eackermann** [comment]
So what's the proposed enhancement? Yes, ydata is (n_signals, n_samples) and timestamps is of shape (n_samples). Is there still something to be said here, or can we close this issue?

I don't see how we can meaningfully support or even interpret the case you mentioned, although I do agree that the naming convention (AnalogSignalArray) could suggest that we can bundle together arbitrary analog signals, which is not true.

A different collection object is perhaps needed, but so far I haven't really had the need for such an object.

@shayokdutta final thoughts? Shall we close as no longer relevant?

**Comment by eackermann** [comment]
Closing as no longer relevant. AnalogSignalArrays do not support jagged arrays.
