### ISSUE TITLE
Consider renaming (globally) fs and to add fs_new as meta data

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#117]

**Comment by shayokdutta** [comment]
FYI: I currently have this as fs_meta in ASA and it isn't used for any calculations

**Comment by eackermann** [comment]
This is becoming critical, at least insofar as we must treat ASA.fs very carefully---it is used in filtering, smoothing, etc.

**Comment by eackermann** [comment]
Stale issue.
