### ISSUE TITLE
generate synthetic test data

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#154]
- [ ] synthetic spikes @eackermann @jchutrue 
- [ ] synthetic lfp @shayokdutta 
- [ ] synthetic trajectories @eackermann @sillyproject 
- [ ] synthetic ripples @shayokdutta
- [ ] synthetic tuning curves
- [ ] synthetic imaging data @jjuneau @ziyingc 
- [ ] synthetic ...?

- [ ] joint neural and behavioral data synthesis?

**Comment by shayokdutta** [comment]
What do you want synthetic data with/for? I mean can I just share a npz file of synthetic ripples and example CA1 LFP?

**Comment by eackermann** [comment]
It is often nice to be able to synthesize data. I hardly think I need to motivate that any further.

If people don't have LFP, then it'll be nice to simply synthesize some, in order to try out nelpy. Synthesizing is way more flexible than loading an example file. It also takes up much less space.

Some of the other types of data might be slightly more interesting to simulate / synthesize, but lfp certainly has its place, too.

**Comment by eackermann** [comment]
Nelpy is not yet meant for data synthesis, so closing this issue as overly ambitious, or out-of-scope.
