### ISSUE TITLE
Fix up empty AnalogSignalArray

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#206]
In particular, this piece of legacy code was found:

```python
# TODO: this needs to change so that n_signals etc. are preserved
################################################################
if newepochs.isempty:
    warnings.warn("Index resulted in empty epoch array")
    return AnalogSignalArray([], empty=True)
########
```

and there are other instances of this pattern as well, that needs to be cleaned up.

**Comment by jchutrue** [comment]
This has already been fixed:

https://github.com/nelpy/nelpy/blob/abd0cb5fda3afe8fc88a0259e76a1dc472c3c187/nelpy/core/_analogsignalarray.py#L837-L849

Though one question I had was whether `self_dat[:] = np.nan`  is necessary since this array is already empty

**Comment by eackermann** [comment]
I believe you're right, the self._data[:] = np.nan is superfluous, and should be removed.

**Comment by jchutrue** [comment]
I believe line 846 in the snippet I posted above is not entirely correct.
`self._data = np.zeros([0,self.data.shape[0]])` should be `self._data = np.zeros([self.data.shape[0], 0])`? 

Currently indexing by an empty EpochArray ends up in this code block in `__getitem__`:
https://github.com/nelpy/nelpy/blob/abd0cb5fda3afe8fc88a0259e76a1dc472c3c187/nelpy/core/_analogsignalarray.py#L1372-L1374

`empty()` then calls `copy_without_data()`, which looks like this:
https://github.com/nelpy/nelpy/blob/abd0cb5fda3afe8fc88a0259e76a1dc472c3c187/nelpy/core/_analogsignalarray.py#L1390-L1397

Which has the correct shape (n_signals, 0). Thus, the snippet two posts above never gets executed. You can verify this by putting a print statement after line 1374 in _analogsignalarray.py. The method should return before that statement.

As for code organization, maybe we should handle empty EpochArrays in `_restrict_to_interval_array_fast()` and not in `__getitem__()`?
