### ISSUE TITLE
when slicing and restricting BSTs, self-attached metadata gets lost

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#229]
For example,

```
bst = (...)
bst._foo = bar

bst[0]._foo ==> error, atrribute _foo does not exist!
```

**Comment by eackermann** [comment]
Sometimes these attributes are unit specific, or epoch specific, in which case the user has to do manual pruning, but at least we should make the default to leave those in place, independent of the cutting / slicing

**Comment by eackermann** [comment]
Update: this was also a problem in AnalogSignalArrays (and derived classes), but it's been fixed there. It's not fixed yet for BinnedSpikeTrainArrays, but the code has been marked up with `TODO: issue 229`

**Comment by eackermann** [comment]
Another fun one. It's been fixed in EpochArrays, RegularlySampledAnalogSignalArrays, EventArrays, ... but not BinnedSpikeTrainArrays. As with several things (epoch restriction, full slice indexing, ...) BSTs have been neglected, since the other object types were "even more fundamental", and I had workarounds to get what I wanted. But the BST should be a first-class citizen, and should get brought up to par with the rest of the core objects.

Several other issues should likely be spawned (e.g. epoch restriction, slice index overhaul, etc), if they don't exist already.

**Comment by jchutrue** [comment]
As of 89414fd0ce6896db5bd10da8ee78ada7cc06571c, this is now implemented and tested

**Comment by jchutrue** [comment]
Also done!
