### ISSUE TITLE
Refactor ASA.downsample() to make use of new filtering module

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#240]

**Comment by jchutrue** [comment]
ASAs do use the filtering module to downsample, although indirectly through utils.downsample_analogsignalarray(). Thus, this issue can probably be closed. Further discussion can go in #275

**Comment by eackermann** [comment]
I agree that this issue should be closed. For a while, we actually had filtering code inside utils.downsample, so that a refactoring was really necessary (but it's been completed at some point, without updating the issue).
