### ISSUE TITLE
EpochDataSlicer remembers old parent

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#244]
This is interesting...

```python
sig = nel.AnalogSignalArray(ydata=[[1,2,4,8,15,6,7,4,3,10],[10,11,13,14,15,16,17,18,19,110]], timestamps=np.array([1,2,3,5,6,7,11,12,13,14])/5)
```
now `sig` is an `AnalogSignalArray` with a `DataSlicer` object (`epochdata`) attached to it, which has an internal `_parent` pointing to `sig`.

If we modify `sig`, e.g. `newsig = sig + 5`, then `newsig.ydata` etc. are updated properly, but now  `newsig._epochdata._parent` still points to `sig` and not to `newsig`, so that the data slicer returns the original data, and not the mutated data in `newsig`.

Is there an easy solution without much bookkeeping? Or should I check for EVERY instance where data is mutated or a copy is returned, and then reassign the slicer's parent?

This bug can be really tricky to trace, and I first noticed it when plotting something, where the plot was no longer related to any of the data in the object :/

**Comment by eackermann** [comment]
Somewhat related to this, is that if I cast `AnalogSignalArray`s to `PositionArray`s and back (and presumably things like `IMUSensorArray` etc., then we also need a way to update and/or initialize the slicers.

**Comment by eackermann** [comment]
Current fix is to call a self.__renew__() whenever data is mutated, but I haven't implemented this fix system-wide yet

**Comment by eackermann** [comment]
@jchutrue since you'll need to understand the internals, this is a fun one to dig into. I don't actually know if this is still relevant after the migration to the generalized object types (that was essentially a complete overhaul and re-write of all the core objects), so we need to check. The comment thread is sufficiently detailed to reconstruct the issue though, if needed (and indeed if it still exists).

At any rate, if this fix is still necessary and not system-wide, it better become system-wide soon! Because all the indexing ans slicing relies on this ==> core functionality.

**Comment by jchutrue** [comment]
This is no longer an issue with the core objects, since their `copy()` methods call `__renew__()`. The exception is the interval array, whose class definition does not have a `__renew__()` (no need to), and whose `copy()` is the following:
https://github.com/nelpy/nelpy/blob/abd0cb5fda3afe8fc88a0259e76a1dc472c3c187/nelpy/core/_intervalarray.py#L619-L626

Can this be simplified to `copy.deepcopy(self)` to be consistent with the `copy()` method of all the other core objects?

**Comment by eackermann** [comment]
Yes. Changed, and closing.
