### ISSUE TITLE
Notch filter not implemented in nelpy.filtering.sosfiltfilt

### ISSUE THREAD

**Issue by avrodriguez** [nelpy/nelpy#250]
Trying to do passband filter between 2 and 100 Hz, but also perform a notch filter to remove 60 Hz noise.

**Comment by eackermann** [comment]
`bandpass=True` parameter added to `sosfiltfilt`. If `bandpass=False`, then filter becomes a bandstop (notch) filter instead of a bandpass filter.

For example,
```
sosfiltfilt(asa, fl=10) # highpass with passband 10 Hz and up
sosfiltfilt(asa, fh=10) # lowpass with passband 0 to 10 Hz

sosfiltfilt(asa, fl=10, bandpass=False) # stopband 10 Hz and up (= lowpass up to 10 Hz)
sosfiltfilt(asa, fh=10, bandpass=False) # stopband up to 10 Hz (= highpass 10 Hz and up)
```

**Comment by eackermann** [comment]
@avrodriguez does this syntax make sense? other recommendations? 

let me know if this gives the expected results, similar to your Matlab script!

**Comment by eackermann** [comment]
So very concretely, you'll do
```python
filtered = nel.filtering.sosfiltfilt(asa, fl=2, fh=100) # filter signal to be between 2 and 100 Hz
filtered = nel.filtering.sosfiltfilt(filtered, fl=59, fh=61, bandpass=False) # remove 60 Hz component
```

**Comment by eackermann** [comment]
@avrodriguez maybe it's more readable if we change the syntax to be `bandstop=True` instead of `bandpass=False`?

So that your requested filter would be
```python
filtered = nel.filtering.sosfiltfilt(asa, fl=2, fh=100) # filter signal to be between 2 and 100 Hz
filtered = nel.filtering.sosfiltfilt(filtered, fl=59, fh=61, bandstop=True) # remove 60 Hz component
```
