### ISSUE TITLE
Changing the support on BinnedEventArrays does not propagate to binnedSupport

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#268]
For example, 
```python
bst_train.support = bst_train.support.merge()
```
updates the support (and trims the data, presumably?) but does not patch up the `binnedSupport`. A workaround is again by casting to an `AnalogSignalArray` first, but when I have time I should just implement this fix directly.

**Comment by eackermann** [comment]
@jchutrue this is confirmed fixed now, right?

**Comment by jchutrue** [comment]
Correct, changing the support triggers restriction, which then updates the binnedSupport

**Comment by eackermann** [comment]
Nice! Closing then.
