### ISSUE TITLE
Update downsample_analogsignalarray to RegularlySampledAnalogSignalArray

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#275]
Similarly, modify asa.time access.

Would like to do this with you, @jchutrue , so that we're on the same page.

**Comment by jchutrue** [comment]
Since we agreed in #271 to support only nelpy objects (specifically ASAs) for downsampling, we can simply make utils.downsample_analogsignalarray() into an ASA class method

**Comment by eackermann** [comment]
I agree with this. Is the one in utils already smart enough to figure out it's own type using introspection? I think so, but we need to check before we can move it and close this issue.

**Comment by jchutrue** [comment]
Yes, it checks that the input object is an ASA, and anyway when we make it an ASA class method, we won't have to check any longer

**Comment by eackermann** [comment]
No, it seems inadequate. It checks for core.AnalogSignalArray, which is not the generic type. And it modifies asa._data and asa._time, which is also largely deprecated. So my original comment from when I opened this issue still holds true.

**Comment by jchutrue** [comment]
There is no need to check the type once we convert it into a class method. Right, ._time is deprecated, but ._data isn't

**Comment by eackermann** [comment]
the class method still calls sosfiltering, which checks for core.AnalogSignalArray. All instances of such checks should be updated, so maybe it's worth it's own issue? But it's still relevant here. But yes, asa._data is stil relevant.

**Comment by eackermann** [comment]
Just so it's clear from these comments: right now, it ONLY works for an (old-fashioned and pure) AnalogSignalArray. But it doesn't work for PositionArrays, or IMUSensorArrays, or any other non-standard or specialized RegularlySampledAnalogSignalArrays. 

And there's no reason it shouldn't work. The code just needs a tiny amount of modification to work for ANY RegularlySampledAnalogSignalArray. That is the reason for this issue (and hence it's title).

**Comment by jchutrue** [comment]
Agreed, type checking in sosfiltfilt and downsample should be updated. Alternatively, there is potentially a case for converting the filtering code into a class method as well, since only RSASAs use it?

**Comment by jchutrue** [comment]
But getsos() doesn't really belong in an ASA, so maybe we'll keep the filtering code in a separate module still

**Comment by eackermann** [comment]
sosfiltfilt also works on lists or arrays. It's one of the few places where we elected to support more than nelpy objects. I want to keep it that way, because I personally think that the sosy filter is superior to the few-tap Butterworth filters used in neuroscience, and I'm not aware of anyone else ever using sosy filters

**Comment by eackermann** [comment]
So I don't know that it's worth spawning its own package, but if other people can easily use our filters to say, replicate our ripple detection exactly, then that's a win for me

**Comment by eackermann** [comment]
I definitely don't want filtering as a class method though

**Comment by jchutrue** [comment]
Agreed. As for this particular issue, it should be a quick fix

**Comment by jchutrue** [comment]
Filtering accepts any RegularlySampledAnalogSignalArray type now, instead of just AnalogSignalArray. Update is on all branches
