### ISSUE TITLE
Issue warnings / raise exceptions when casting to BST from ASA

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#278]
In particular, if ASA has empty epochs, then those should be dropped prior to casting.

Also, if ASA has an overlapping support, then we should merge those before casting.

No bugs here, but warnings / exceptions will be nice.

This should probably go in the casting section of BinnedEventArray.

**Comment by jchutrue** [comment]
Implementing this but running into issues. 

If we have an epoch array `ep` with overlapping epochs, and we make an ASA `y = asa[ep]`, then `y.support.ismerged` is `False` as expected. But if we then have `z = y[y.support.merge()]`, `z.support.ismerged` still returns `False`. Yet `z` and `y` are different objects. Where am I going wrong?

**Comment by eackermann** [comment]
This seems perfectly logical to me. Maybe I don't fully understand your Q.

If you restrict an unmerged object by a merged object, why would you expect the result to be merged?

More concretely, if we have [0, 5) U [2, 7), then clearly they are ovelapping. If we then restrict these by (-infty, infty), which is merged, we would expect to get [0, 5) U [2, 7) back again, which is not merged.

Similarly, [0, 5) U [2, 7) restricted to [1, 6) would most naturally result in [1, 5) U [2, 6), and indeed it does.

@jchutrue what behavior were you expecting, and why?

**Comment by eackermann** [comment]
More to the point, `y[y.support.merge()]` is a nonsensical statement in my mind; y is already restricted to it's own support. So what would you gain by restricting it to it's support again? You should just get `y` back. And indeed you do. 

So I'm lost on what you're trying to do here.

**Comment by jchutrue** [comment]
This explanation makes sense. In your example above, I was hoping `z = y[y.support.merge()]` would result in an object `z` whose support was [1, 6)

**Comment by eackermann** [comment]
then the machinery to do that is of course to say `z = y.copy(); z.support = z.support.merge()`

**Comment by jchutrue** [comment]
Thanks, that helped

**Comment by eackermann** [comment]
This issue can also be closed now, right @jchutrue ?

**Comment by jchutrue** [comment]
Correct

**Comment by eackermann** [comment]
:+1:
