### ISSUE TITLE
Fix empty event arrays

### ISSUE THREAD

**Issue by jchutrue** [nelpy/nelpy#280]
Similar to #206, empty event arrays lose information such as `n_series`.

**Comment by eackermann** [comment]
@jchutrue this is fixed, too, right?

**Comment by jchutrue** [comment]
@eackermann correct, calling `empty()` preserves that information and any additional metadata, and we have a test for this. Note that this is different from constructor an object with empty=True

**Comment by eackermann** [comment]
Very good! And we don't use the empty=True pattern internally anywhere in eventarray.py, so we're good to go.
