### ISSUE TITLE
Implement epoch and unit slicing directly for BinnedEventArrays

### ISSUE THREAD

**Issue by jchutrue** [nelpy/nelpy#283]
The current solution is to cast to an RSASA, restrict there, then cast back to BEVA. We should do this directly, and ensure no user-defined metadata gets lost in the process. See #229 for more info.

**Comment by jchutrue** [comment]
Implemented and tested since 89414fd0ce6896db5bd10da8ee78ada7cc06571c

**Comment by jchutrue** [comment]
@eackermann this can also be closed out

**Comment by eackermann** [comment]
Sweet! Don't be afraid to close the issues yourself, Josh!
