### ISSUE TITLE
Memory leak when creating ASAs repeatedly

### ISSUE THREAD

**Issue by jchutrue** [nelpy/nelpy#287]
Suppose we have an ASA that we merely want to copy. If I run this code:

    for ii in range(10):
        out = nel.AnalogSignalArray(asa.data, abscissa_vals=asa.abscissa_vals, fs=asa.fs)

then the memory usage increases in proportional to how many iterations I run the loop. 

If the code is changed to 

    for ii in range(10):
        out = nel.AnalogSignalArray(asa.data, abscissa_vals=asa.abscissa_vals, fs=asa.fs)
        del out

the memory usage is still the same as the original code block.

At every iteration, the only thing we expect to happen is that `out` gets bound to a new object created by `nel.AnalogSignalArray`, but it seems that the ASAs constructed in other loop iterations remain in memory.

I'm not sure yet whether this is an issue with nelpy itself, or if it's an issue with Python garbage collection.

**Comment by eackermann** [comment]
On a Windows machine at least, this seems like a garbage collector issue. After a while of accumulation, the memory usage drops sharply back to baseline.

**Comment by jchutrue** [comment]
Same thing observed on a Linux machine, probably not a nelpy issue.
