### ISSUE TITLE
ASA evaluatiuon fails for single argument

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#294]
asa(10) fails with ```IndexError: tuple index out of range```, whereas ```asa((5,6,7))``` works.

```asa.asarray(at=10)``` also fails, but ```eeg.asarray(at=[10])``` works

We need to write a test to catch this in the future, and we need to trace and correct the current issue. This used to work relatively recently (two months ago?) and I'm not sure yet if it's due to something we did, or due to some of the more recent Python 3.7 and/or numpy updates.

**Comment by eackermann** [comment]
@jchutrue please check if this fails for you, too, since you're running an older system than me.

**Comment by jchutrue** [comment]
Fixed on `develop` and `unstable` branches
