### ISSUE TITLE
Tricky changes to _restrict_to_epoch_array

### ISSUE THREAD

**Issue by eackermann** [nelpy/nelpy#52]
In `SpikeTrainArray._restrict_to_epoch_array`

```
# Potential BUG: not sure if time and samples point to same
# object (like when only time was passed to __init__), then
# doing samples[unit] = ... followed by time[unit] = ... might
# be applying the shrinking twice, no? We need a thorough test
# for this! And I need to understand the shared memory 100%.
```
and how does `copy = False` affect the behavior?

**Comment by eackermann** [comment]
Seems to be stable so far, but I noticed that @shayokdutta copied my old code which changed self. Re-think situation for AnalogSignal as well

**Comment by shayokdutta** [comment]
Good eye! I will take a look soon!

**Comment by eackermann** [comment]
Closed as no longer relevant.
